/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package frc.team6027.robot.client;

import org.apache.logging.log4j.Logger;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.Socket;

import org.apache.logging.log4j.LogManager;

// import com.pi4j.io.gpio.GpioController;

public class PiRequestClient {
    private final static Logger logger = LogManager.getLogger(PiRequestClient.class);
    public static final String SERVER_ADDRESS = "192.168.254.99";//"localhost";

    public String getGreeting() {

        return "Hello world.";
    }

    public static void main(String[] args) {
        long startTime = System.currentTimeMillis();
        long endTime = startTime;
        try (
            Socket socket = new Socket(SERVER_ADDRESS, 5806);
            OutputStream os = socket.getOutputStream();
            PrintWriter toPi = new PrintWriter(os, true);
            
            InputStreamReader inR = new InputStreamReader(socket.getInputStream());
            BufferedReader fromPi = new BufferedReader(inR);

        ) {
            toPi.println("ultrasonic;1");
            String distanceStr = fromPi.readLine();
            endTime = System.currentTimeMillis();
            System.out.println("Distance from Pi: " + distanceStr);

        } catch (IOException e) {
            e.printStackTrace();
        }
        System.out.println("Time to process: " + (endTime - startTime));
    }
}
